version: '2'
services:
  mysql:
    image: mysql:5.7
    container_name: test-mysql
    ports:
      - 6603:3306
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "testuser1"
      MYSQL_PASSWORD: "123456"
    volumes:
      - ./storage/docker/mysql-data:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: auto-test/Dockerfile
    container_name: test-app
    working_dir: /usr/src/app
    command: /bin/bash startup.sh
    volumes:
      - ./auto-test:/usr/src/app
    ports:
      - "32768:3000"
    depends_on:
      - mysql